workflows:
  logs:
    enabled: true
    host: "http://localhost"
    port: 8090
    endpoint: "/logs/{id}"
  metrics:
    enabled: true
    host: "http://localhost"
    port: 8090
    endpoint: "/metrics/{id}"
  incidents:
    enabled: false
    host: "http://localhost"
    port: 8090
    endpoint: "/incidents/{id}"
  operations:
    enabled: true
    host: "http://localhost"
    port: 8090
    endpoint: "/operations/{id}"


clients:
  anthropic:
    key: "your-anthropic-key"

database:
  connection_string: "not required for this version"