workflows:
  logs:
    enabled: true
    host: "localhost"
    port: 8080
    endpoint: "/logs/{id}"
  metrics:
    enabled: true
    host: "localhost"
    port: 9090
    endpoint: "/metrics/{id}"
  incidents:
    enabled: true
    host: "localhost"
    port: 7070
    endpoint: "/incidents/{id}"
  operations:
    enabled: true
    host: "localhost"
    port: 6060
    endpoint: "/operations/{id}"


clients:
  anthropic:
    key: "your-anthropic-api-key"

database:
  connection_string: postgresql://harshadmanglani@localhost:5432/postgres?sslmode=disable